- name: BSE — price > 1 (1d)
  symbol: BSE
  kind: price
  timeframe: "1d"
  op: gt
  value: 1

- name: BSE — RSI crosses 70 down (1d)
  symbol: BSE
  kind: indicator
  timeframe: "1d"
  indicator: rsi
  op: crosses_below
  value: 70
  params: { length: 14 }

- name: GODFRYPHLP — Bullish Engulfing (1d)
  symbol: GODFRYPHLP
  kind: pattern
  timeframe: "1d"
  pattern: bullish_engulfing

# (optional) EMA check on daily too
- name: BSE — EMA21 rising (1d)
  symbol: BSE
  kind: indicator
  timeframe: "1d"
  indicator: ema
  op: gt
  value: 0
  params: { length: 21 } # your overlays.ema can emit slope or level; if slope, compare to 0

- name: BSE — EMA21 rising (slope>0, 1d)
  symbol: BSE
  kind: indicator
  timeframe: "1d"
  indicator: ema_slope
  op: gt
  value: 0
  params:
    length: 21
    periods: 1
