# queen/configs/alert_intraday_rules.yaml
# Intraday rules — best during live session (or use --force-closed + --backfill-days).

rules:
  # 1) Intraday price (green card)
  - name: "BSE — price > 1 (5m)"
    symbol: "BSE"
    kind: "price"
    timeframe: "5m"
    op: "gt"
    value: 1

  # 2) Intraday RSI cross (red/green cross logs + card when it actually crosses)
  - name: "BSE — RSI crosses 70 down (5m)"
    symbol: "BSE"
    kind: "indicator"
    indicator: "rsi"
    timeframe: "5m"
    op: "crosses_below"
    value: 70
    params:
      length: 14

  # 3) Keep a daily pattern alongside intraday to see purple cards any time
  - name: "GODFRYPHLP — Bullish Engulfing (1d)"
    symbol: "GODFRYPHLP"
    kind: "pattern"
    pattern: "bullish_engulfing"
    timeframe: "1d"
