# Oversold tag + recovery
- name: NSDL RSI < 30
  symbol: NSDL
  kind: indicator
  indicator: rsi
  timeframe: 1d
  op: lt
  value: 30
  params: { length: 14 }

- name: NSDL RSI crosses 30 up
  symbol: NSDL
  kind: indicator
  indicator: rsi
  timeframe: 1d
  op: crosses_above
  value: 30
  params: { length: 14 }
